### ISSUE TITLE
laanp-BuildersDream

### ISSUE THREAD

**Issue by 000afterlife000** [laanp/Icarus_Mods_Separated#1]
The laanp-BuildersDream which i must say is amazing, after a steam update today the mod now causes the game to crash, I have downloaded the latest version of the mod, and the game will not run unless i take the mod out,  anyone else having this issue, as i am really missing not having this mod

Richard

**Comment by laanp** [comment]
Should be updated now, gotta wait till I get out of bed, I am on west coast  !!
