### ISSUE TITLE
Campfire not cooking meat

### ISSUE THREAD

**Issue by physguyk** [laanp/Icarus_Mods_Separated#3]
With laanp-StacksAndKits, laanp-PetesAuxSlots, and laanp-PowerSurge installed (via IMM 2.2.3) on Hotfix Version: 2.2.23.128261-rel-Laika, putting meat (maybe other things, but that's what I've tested) into a lit (with wood) campfire doesn't actually cook, just sits there. Removing just PowerSurge gets it to behave again and cook meat like usual. Figured you'd want to know. Thanks for all you do with these mods!

**Comment by laanp** [comment]
Will have a look, thanks for reporting!

**Comment by laanp** [comment]
Doesn't make sense, as those mods do not touch anything to do with cooking or the campfire.  I just tried all (3) of those mods with IMM 2.2.3 and latest hotfix and my meat cooks ok in the fire.
Check your version of the mods, get my latest from my github at: https://github.com/laanp/Icarus_Mods_Separated
should be `<modname>_vX_w148_P.pak` and make sure you click 'Update Data Folder` in IMM before recompiling and merging the mods.

**Comment by physguyk** [comment]
Update Database and then Refresh Local Files, then Remove All Mods from Game, then re-applying the three listed above didn't help, but removing them from IMM entirely and then re-downloading them individually, then removing all and installing did work. Not sure what's going on, but seems like maybe something with IMM or maybe file corruption. Either way, I'm good to go now. Thanks for the quick response!
