### ISSUE TITLE
Circle Builder

### ISSUE THREAD

**Issue by dpfaff7933** [laanp/Icarus_Mods_Separated#5]
Hello!
First of this in incredible.  I had searched out your videos in reference to building before I saw that you had these Mods.  Icarus is my favorite Game of all time! These mods are exceptional and make the game fresh for me.  However, I am rocking the QOL mod and it's amazing! Unless I use the circle Builder.  Is it known to you that you can't use circle builder when using the QOL mod? Is it possible and I'm doing something wrong?
Thank you,
Andrew 
PS how can I donate to you? I feel like all this work and dedication warrants it

**Comment by laanp** [comment]
Hey, thanks for the kind feedback!
You can absolutely use both mods together, but like any mix and match you want to do with mods, you need to use the Icarus Mod Manager (IMM) by user Jimk72.
That utility is required to properly merge mods that impact the same files.
Get it here: https://github.com/Jimk72/Icarus_Software/blob/main/Icarus_Mod_Manager_2_2_1.zip
Make sure you update this version once installed, search Youtube for instructions 

I do modding for the love of the game, and wish to share my work at no cost to the community, but I thank you for your desire to contribue!
